version: '3'
services:
        broker:
                image: mineduino/broker 
                ports:
                - 1883:1883
                - 9001:9001
        clientdht:
                image: mineduino/client
                environment:
                - TYPE=dht12
                - MQTTIP=broker
                - MQTTPORT=1883
                - TOPIC=/temperature
        clientbutton:
                image: mineduino/client
                environment:
                - TYPE=button
                - MQTTIP=broker
                - MQTTPORT=1883
                - TOPIC=/button

